import { z } from "zod";
export const dateSchema = z.iso.date();
const text = (max: number) => z.string().trim().min(1).max(max);
export const areaInput = z.object({ name: text(80), color: z.string().max(30).nullable().optional(), icon: z.string().max(40).nullable().optional(), position: z.number().int().min(0).optional() }).strict();
const schedule = z.discriminatedUnion("schedule_type", [
  z.object({ schedule_type: z.literal("DAILY"), schedule_config: z.object({}).strict() }),
  z.object({ schedule_type: z.literal("WEEKDAYS"), schedule_config: z.object({ weekdays: z.array(z.number().int().min(0).max(6)).min(1).max(7) }).strict() }),
  z.object({ schedule_type: z.literal("WEEKLY_TARGET"), schedule_config: z.object({ target: z.number().int().min(1).max(7) }).strict() }),
  z.object({ schedule_type: z.literal("MONTHLY_TARGET"), schedule_config: z.object({ target: z.number().int().min(1).max(31) }).strict() }),
  z.object({ schedule_type: z.literal("INTERVAL"), schedule_config: z.object({ interval: z.number().int().min(1).max(365) }).strict() }),
]);
export const habitInput = z.object({ name: text(120), description: z.string().max(2000).nullable().optional(), area_id: z.uuid().nullable().optional(), type: z.enum(["GOOD", "BAD"]), tracking_type: z.enum(["BOOLEAN", "MEASURABLE"]), goal_value: z.number().positive().max(1e9).nullable().optional(), minimum_goal_value: z.number().positive().max(1e9).nullable().optional(), stretch_goal_value: z.number().positive().max(1e9).nullable().optional(), quick_increments: z.array(z.number().positive().max(1e9)).min(1).max(5).nullable().optional(), unit: z.string().trim().max(40).nullable().optional(), start_date: dateSchema, end_date: dateSchema.nullable().optional(), color: z.string().max(30).nullable().optional(), icon: z.string().max(40).nullable().optional(), position: z.number().int().min(0).optional(), time_of_day: z.enum(["MORNING", "AFTERNOON", "EVENING", "ANYTIME"]).optional(), priority: z.enum(["LOW", "NORMAL", "HIGH"]).optional(), difficulty: z.enum(["EASY", "MODERATE", "HARD"]).nullable().optional() }).and(schedule).refine(v => v.tracking_type === "BOOLEAN" || (v.goal_value != null && Boolean(v.unit)), "Measured habits need a goal and unit").refine(v => !v.end_date || v.end_date >= v.start_date, "End date must follow start date").refine(v => v.tracking_type === "MEASURABLE" || (!v.minimum_goal_value && !v.stretch_goal_value && !v.quick_increments), "Goal tiers and increments need a measured habit").refine(v => v.minimum_goal_value == null || (v.goal_value != null && v.minimum_goal_value <= v.goal_value), "Minimum cannot exceed target").refine(v => v.stretch_goal_value == null || (v.goal_value != null && v.goal_value <= v.stretch_goal_value), "Stretch cannot be below target").refine(v => !v.quick_increments || new Set(v.quick_increments).size === v.quick_increments.length, "Quick increments must be unique");
export const logInput = z.object({ habit_id: z.uuid(), date: dateSchema, status: z.enum(["COMPLETED", "FAILED", "SKIPPED"]).nullable(), value: z.number().min(0).max(1e9).nullable().optional(), reason: z.string().trim().max(120).nullable().optional() }).strict();
export const pauseInput = z.object({ start_date: dateSchema, end_date: dateSchema.nullable().optional(), reason: z.string().trim().max(80).nullable().optional(), note: z.string().trim().max(500).nullable().optional() }).strict().refine(value => !value.end_date || value.end_date >= value.start_date, "Pause end must follow start");
export const relationshipInput = z.object({ source_habit_id: z.uuid(), target_habit_id: z.uuid(), type: z.literal("AFTER") }).strict().refine(value => value.source_habit_id !== value.target_habit_id, "A habit cannot follow itself");
export const noteInput = z.object({ habit_id: z.uuid(), date: dateSchema.nullable().optional(), content: text(4000) }).strict();
export const reminderInput = z.object({ habit_id: z.uuid(), time: z.iso.time(), timezone: text(80), enabled: z.boolean().default(true) }).strict();
export const profileInput = z.object({ timezone: text(80).optional(), theme: z.enum(["light", "dark", "system"]).optional() }).strict();
