"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Area } from "@/lib/domain";
export function AreasManager({ initial, counts }: { initial: Area[]; counts: Record<string, number> }) { const router = useRouter(); const [areas, setAreas] = useState(initial); const [error, setError] = useState("");
  async function add(event: React.SubmitEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const name = String(new FormData(form).get("name")); const response = await fetch("/api/v1/areas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, position: areas.length }) }); const body = await response.json(); if (response.ok) { setAreas([...areas, body.area]); form.reset(); router.refresh(); } else setError(body.error); }
  async function rename(area: Area) { const name = prompt("Area name", area.name); if (!name || name === area.name) return; const response = await fetch(`/api/v1/areas/${area.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json(); if (response.ok) { setAreas(areas.map(a => a.id === area.id ? body.area : a)); router.refresh(); } else setError(body.error); }
  async function remove(area: Area) { if (!confirm(`Delete ${area.name}? Its habits will become uncategorized.`)) return; const response = await fetch(`/api/v1/areas/${area.id}`, { method: "DELETE" }); if (response.ok) { setAreas(areas.filter(a => a.id !== area.id)); router.refresh(); } else setError("Unable to delete area."); }
  async function move(area: Area, delta: number) { const index = areas.findIndex(a => a.id === area.id), next = index + delta; if (next < 0 || next >= areas.length) return; const reordered = [...areas]; [reordered[index], reordered[next]] = [reordered[next], reordered[index]]; setAreas(reordered); const result = await Promise.all(reordered.map((a, position) => fetch(`/api/v1/areas/${a.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ position }) }))); if (result.some(r => !r.ok)) setError("Could not save order."); router.refresh(); }
  return <><form className="actions" onSubmit={add}><div className="field"><label htmlFor="area-name">New area</label><input id="area-name" name="name" maxLength={80} placeholder="e.g. Health" required/></div><button className="button primary" style={{ alignSelf: "end" }}>Add area</button></form>{error && <p role="alert" className="form-error">{error}</p>}<h2 className="section-title">Your areas</h2>{areas.length ? <div className="list">{areas.map(area => <div className="card row" key={area.id}><div><b>{area.icon} {area.name}</b><p className="subtle">{counts[area.id] ?? 0} active habits</p></div><div className="actions"><button className="button small" aria-label={`Move ${area.name} up`} onClick={() => move(area, -1)}>↑</button><button className="button small" aria-label={`Move ${area.name} down`} onClick={() => move(area, 1)}>↓</button><button className="button small" onClick={() => rename(area)}>Edit</button><button className="button small danger" onClick={() => remove(area)}>Delete</button></div></div>)}</div> : <div className="card empty"><h2>No areas yet</h2><p>Group related habits to see progress by area.</p></div>}</>;
}
