"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { Area, Habit, ScheduleType } from "@/lib/domain";
export function HabitForm({ areas, today, habit }: { areas: Area[]; today: string; habit?: Habit }) {
  const router = useRouter(); const [schedule, setSchedule] = useState<ScheduleType>(habit?.schedule_type ?? "DAILY"); const [tracking, setTracking] = useState(habit?.tracking_type ?? "BOOLEAN"); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget);
    const weekdays = [0,1,2,3,4,5,6].filter(day => form.get(`weekday-${day}`) === "on");
    const schedule_config = schedule === "WEEKDAYS" ? { weekdays } : schedule === "INTERVAL" ? { interval: Number(form.get("interval")) } : schedule === "WEEKLY_TARGET" || schedule === "MONTHLY_TARGET" ? { target: Number(form.get("target")) } : {};
    const body = { name: form.get("name"), description: form.get("description") || null, area_id: form.get("area_id") || null, type: form.get("type"), tracking_type: tracking, goal_value: tracking === "MEASURABLE" ? Number(form.get("goal_value")) : null, unit: tracking === "MEASURABLE" ? form.get("unit") : null, schedule_type: schedule, schedule_config, start_date: form.get("start_date"), end_date: form.get("end_date") || null, icon: form.get("icon") || null, color: form.get("color") || null };
    try { const response = await fetch(habit ? `/api/v1/habits/${habit.id}` : "/api/v1/habits", { method: habit ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw Error(data.error); router.push(`/habits/${data.habit.id}`); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save habit."); } finally { setPending(false); }
  }
  return <form className="form" onSubmit={submit}><div className="field"><label htmlFor="name">Habit name</label><input id="name" name="name" defaultValue={habit?.name} maxLength={120} placeholder="e.g. Read 30 pages" required autoFocus/></div><div className="form-grid"><div className="field"><label htmlFor="type">Habit type</label><select id="type" name="type" defaultValue={habit?.type ?? "GOOD"}><option value="GOOD">Build a good habit</option><option value="BAD">Reduce a bad habit</option></select></div><div className="field"><label htmlFor="tracking">Tracking</label><select id="tracking" name="tracking" value={tracking} onChange={e => setTracking(e.target.value as Habit["tracking_type"])}><option value="BOOLEAN">Yes or no</option><option value="MEASURABLE">Measured amount</option></select></div></div>
  {tracking === "MEASURABLE" && <div className="form-grid"><div className="field"><label htmlFor="goal_value">Goal amount</label><input id="goal_value" name="goal_value" type="number" min="0.001" step="any" defaultValue={habit?.goal_value ?? ""} required/></div><div className="field"><label htmlFor="unit">Unit</label><input id="unit" name="unit" placeholder="pages, L, steps…" defaultValue={habit?.unit ?? ""} required/></div></div>}
  <div className="form-grid"><div className="field"><label htmlFor="schedule">Schedule</label><select id="schedule" value={schedule} onChange={e => setSchedule(e.target.value as ScheduleType)}><option value="DAILY">Every day</option><option value="WEEKDAYS">Specific weekdays</option><option value="WEEKLY_TARGET">Times per week</option><option value="MONTHLY_TARGET">Times per month</option><option value="INTERVAL">Every N days</option></select></div><div className="field"><label htmlFor="start_date">Start date</label><input id="start_date" name="start_date" type="date" defaultValue={habit?.start_date ?? today} required/></div></div>
  {schedule === "WEEKDAYS" && <fieldset className="field"><legend>On these days</legend><div className="checkboxes">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day, i) => <label key={day}><input name={`weekday-${i}`} type="checkbox" defaultChecked={habit?.schedule_config.weekdays?.includes(i) ?? (i > 0 && i < 6)}/> {day}</label>)}</div></fieldset>}
  {(schedule === "WEEKLY_TARGET" || schedule === "MONTHLY_TARGET") && <div className="field"><label htmlFor="target">Times per {schedule === "WEEKLY_TARGET" ? "week" : "month"}</label><input id="target" name="target" type="number" min="1" max={schedule === "WEEKLY_TARGET" ? 7 : 31} defaultValue={habit?.schedule_config.target ?? 3} required/></div>}
  {schedule === "INTERVAL" && <div className="field"><label htmlFor="interval">Every how many days?</label><input id="interval" name="interval" type="number" min="1" max="365" defaultValue={habit?.schedule_config.interval ?? 2} required/></div>}
  <details><summary>More options</summary><div className="form" style={{ paddingTop: 15 }}><div className="field"><label htmlFor="area_id">Area</label><select id="area_id" name="area_id" defaultValue={habit?.area_id ?? ""}><option value="">Uncategorized</option>{areas.map(area => <option key={area.id} value={area.id}>{area.name}</option>)}</select></div><div className="field"><label htmlFor="description">Description</label><textarea id="description" name="description" rows={3} defaultValue={habit?.description ?? ""}/></div><div className="form-grid"><div className="field"><label htmlFor="end_date">End date</label><input id="end_date" name="end_date" type="date" defaultValue={habit?.end_date ?? ""}/></div><div className="field"><label htmlFor="icon">Icon or emoji</label><input id="icon" name="icon" maxLength={40} defaultValue={habit?.icon ?? ""}/></div></div><div className="field"><label htmlFor="color">Color</label><input id="color" name="color" type="color" defaultValue={habit?.color ?? "#eb5e28"}/></div></div></details>
  {error && <p className="form-error" role="alert">{error}</p>}<div><button className="button primary" disabled={pending}>{pending ? "Saving…" : habit ? "Save changes" : "Create habit"}</button></div></form>;
}
