"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Note = { id: string; content: string; date: string | null; created_at: string };
export function Notes({ habitId, initial }: { habitId: string; initial: Note[] }) { const router = useRouter(); const [notes, setNotes] = useState(initial); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function add(event: React.SubmitEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = event.currentTarget; const content = String(new FormData(form).get("content")); try { const response = await fetch("/api/v1/notes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ habit_id: habitId, content }) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setNotes([body.note, ...notes]); form.reset(); router.refresh(); } catch(e) { setError(e instanceof Error ? e.message : "Could not add note."); } finally { setBusy(false); } }
  async function remove(id: string) { const response = await fetch(`/api/v1/notes/${id}`, { method: "DELETE" }); if (response.ok) { setNotes(notes.filter(n => n.id !== id)); router.refresh(); } else setError("Could not delete note."); }
  return <><form className="form" onSubmit={add}><div className="field"><label htmlFor="note">Habit note</label><textarea id="note" name="content" maxLength={4000} rows={3} placeholder="What did you notice?" required/></div><div><button className="button" disabled={busy}>Add note</button></div>{error && <p role="alert" className="form-error">{error}</p>}</form><div className="list" style={{ marginTop: 16 }}>{notes.map(note => <div className="card" key={note.id}><div className="row"><small className="muted">{new Date(note.created_at).toLocaleDateString()}</small><button className="button small danger" onClick={() => remove(note.id)}>Delete</button></div><p>{note.content}</p></div>)}</div></>;
}
