import Link from "next/link";
import { notFound } from "next/navigation";
import { appData, logsBetween } from "@/lib/data";
import { calculateHabitStatistics, calculateStreaks } from "@/lib/domain";
import { HabitActions } from "@/components/habit-actions";
import { Notes } from "@/components/notes";
import { Reminders } from "@/components/reminders";
export default async function HabitDetail({ params }: { params: Promise<{ habitId: string }> }) {
  const data = await appData(); const { habitId } = await params; const habit = data.habits.find(h => h.id === habitId); if (!habit) notFound();
  const from = habit.start_date; const ownLogs = await logsBetween(data.user.id, data.client, from, data.today, habit.id); const recentLogs = [...ownLogs].sort((a,b) => b.date.localeCompare(a.date));
  const stats = calculateHabitStatistics(habit, ownLogs, from > habit.start_date ? from : habit.start_date, data.today, data.versions); const streak = calculateStreaks(habit, ownLogs, data.today, data.versions);
  const [notesResult, remindersResult] = await Promise.all([data.client.from("tracker_habit_notes").select("*").eq("user_id", data.user.id).eq("habit_id", habit.id).order("created_at", { ascending: false }).limit(100), data.client.from("tracker_habit_reminders").select("*").eq("user_id", data.user.id).eq("habit_id", habit.id).order("time")]);
  if (notesResult.error || remindersResult.error) throw Error("Unable to load habit details.");
  return <><header className="page-head"><div><p className="eyebrow">HABIT DETAILS</p><h1>{habit.icon ? `${habit.icon} ` : ""}{habit.name}</h1><p className="subtle">{habit.description || "Your progress since you started"}</p></div><Link className="button" href={`/habits/${habit.id}/edit`}>Edit</Link></header><div className="grid"><div className="card stat"><div className="value">{streak.current}</div><div className="label">current streak</div></div><div className="card stat"><div className="value">{streak.best}</div><div className="label">best streak</div></div><div className="card stat"><div className="value">{Math.round(stats.completionRate * 100)}%</div><div className="label">completion rate</div></div></div><h2 className="section-title">Overview</h2><div className="card"><div className="grid"><div><b>Schedule</b><p className="muted">{habit.schedule_type.replaceAll("_", " ").toLowerCase()}</p></div><div><b>Goal</b><p className="muted">{habit.tracking_type === "MEASURABLE" ? `${habit.goal_value} ${habit.unit}` : "Complete once"}</p></div><div><b>Activity</b><p className="muted">{stats.completed} completed · {stats.failed} failed · {stats.skipped} skipped</p></div></div></div><h2 className="section-title">Recent activity</h2><div className="card">{recentLogs.length ? <div className="list">{recentLogs.slice(0,15).map(log => <div className="row" key={log.id}><span>{log.date}</span><span className="pill">{log.status.toLowerCase()}{log.value != null ? ` · ${log.value} ${habit.unit ?? ""}` : ""}</span></div>)}</div> : <p className="muted">No activity recorded yet.</p>}</div><h2 className="section-title">Notes</h2><Notes habitId={habit.id} initial={notesResult.data ?? []}/><h2 className="section-title">Reminders</h2><div className="card"><Reminders habitId={habit.id} timezone={data.timezone} initial={remindersResult.data ?? []}/></div><h2 className="section-title">Manage</h2><div className="card"><HabitActions id={habit.id} archived={habit.is_archived}/></div></>;
}
